//_________________________________________________________________________________________________________________________________________
	package threads;
//_________________________________________________________________________________________________________________________________________
	import gui.lettersoupgui.LetterSoupController;
import javafx.application.Platform;
//_________________________________________________________________________________________________________________________________________
	public class GUIUpdateTimeThread extends Thread{
		
		private LetterSoupController lettersoupcontroller;
	//_____________________________________________________________________________________________________________________________________
		public GUIUpdateTimeThread(LetterSoupController lettersoupcontroller) {
			this.lettersoupcontroller = lettersoupcontroller;
		}
	//_____________________________________________________________________________________________________________________________________
		@Override
		public void run() {
			TimeThread tt = new TimeThread(lettersoupcontroller, false);
			Platform.runLater(tt);
		}	
//_________________________________________________________________________________________________________________________________________
}
	
